ALTER TABLE Books_Genres DROP CONSTRAINT FK__Books_Gen__BookI__47DBAE45;
ALTER TABLE Loans DROP CONSTRAINT FK__Loans__BookID__4E88ABD4;
ALTER TABLE Books_Authors DROP CONSTRAINT FK__Books_Aut__BookI__403A8C7D;
ALTER TABLE Loans DROP CONSTRAINT FK__Loans__BorrowerI__4F7CD00D;
ALTER TABLE Books DROP CONSTRAINT FK__Books__ShelfLoca__3B75D760;
ALTER TABLE Books_Genres DROP CONSTRAINT FK__Books_Gen__Genre__48CFD27E;
ALTER TABLE Books_Authors DROP CONSTRAINT FK__Books_Aut__Autho__412EB0B6;


ALTER TABLE AuditLog DROP CONSTRAINT PK__AuditLog__A17F23B8C6B028E6;
ALTER TABLE Books_Genres DROP CONSTRAINT PK__Books_Ge__8D4DA09675F6E41B;
ALTER TABLE Loans DROP CONSTRAINT PK__Loans__4F5AD4370C40831B;
ALTER TABLE Books DROP CONSTRAINT PK__Books__3DE0C2272260DF96;
ALTER TABLE Borrowers DROP CONSTRAINT PK__Borrower__568EDB77C1B8A543;
ALTER TABLE ShelfLocation DROP CONSTRAINT PK__ShelfLoc__4767083A00ABE0EA;
ALTER TABLE Genres DROP CONSTRAINT PK__Genres__0385055E44DE0E22;
ALTER TABLE Books_Authors DROP CONSTRAINT PK__Books_Au__E6037787DB92DB81;
ALTER TABLE Authors DROP CONSTRAINT PK__Authors__70DAFC140419D5DF;


ALTER TABLE AuditLog ADD CONSTRAINT PK_AuditLog PRIMARY KEY (AuditID);
ALTER TABLE Books_Genres ADD CONSTRAINT PK_Books_Genres PRIMARY KEY (BooksGenresID);
ALTER TABLE Loans ADD CONSTRAINT PK_Loans PRIMARY KEY (LoanID);
ALTER TABLE Books ADD CONSTRAINT PK_Books PRIMARY KEY (BookID);
ALTER TABLE Borrowers ADD CONSTRAINT PK_Borrowers PRIMARY KEY (BorrowerID);
ALTER TABLE ShelfLocation ADD CONSTRAINT PK_ShelfLocation PRIMARY KEY (ShelfLocationID);
ALTER TABLE Genres ADD CONSTRAINT PK_Genres PRIMARY KEY (GenreID);
ALTER TABLE Books_Authors ADD CONSTRAINT PK_Books_Authors PRIMARY KEY (BooksAuthorsID);
ALTER TABLE Authors ADD CONSTRAINT PK_Authors PRIMARY KEY (AuthorID);


ALTER TABLE Books_Genres ADD CONSTRAINT FK_Books_Genres_BookID FOREIGN KEY (BookID) REFERENCES Books(BookID);
ALTER TABLE Loans ADD CONSTRAINT FK_Loans_BookID FOREIGN KEY (BookID) REFERENCES Books(BookID);
ALTER TABLE Books_Authors ADD CONSTRAINT FK_Books_Authors_BookID FOREIGN KEY (BookID) REFERENCES Books(BookID);
ALTER TABLE Loans ADD CONSTRAINT FK_Loans_BorrowerID FOREIGN KEY (BorrowerID) REFERENCES Borrowers(BorrowerID);
ALTER TABLE Books ADD CONSTRAINT FK_Books_ShelfLocation FOREIGN KEY (ShelfLocationID) REFERENCES ShelfLocation(ShelfLocationID);
ALTER TABLE Books_Genres ADD CONSTRAINT FK_Books_Genres_GenreID FOREIGN KEY (GenreID) REFERENCES Genres(GenreID);
ALTER TABLE Books_Authors ADD CONSTRAINT FK_Books_Authors_AuthorID FOREIGN KEY (AuthorID) REFERENCES Authors(AuthorID);


ALTER TABLE Books DROP CONSTRAINT UQ__Books__447D36EA2DD86654;
ALTER TABLE Books ADD CONSTRAINT UQ_Books_ISBN UNIQUE (ISBN);

ALTER TABLE Borrowers DROP CONSTRAINT UQ__Borrower__A9D10534E67AD2C1;
ALTER TABLE Borrowers ADD CONSTRAINT UQ_Borrowers_Email UNIQUE (Email);